__version__ = "0.0.0"
__short_version__ = "0.0"

REFERENCE_DATE = "2022-03-15"

FEATURES_PRICE_MODEL_Q1 = [
    "Categoria",
    "Quartos",
    "year",
    "month",
    "day",
    "holiday",
    "day_of_week_Mon",
    "day_of_week_Sat",
    "day_of_week_Sun",
    "day_of_week_Thu",
    "day_of_week_Tue",
    "day_of_week_Wed",
    "Localização_BOM",
    "Localização_CAM",
    "Localização_CAN",
    "Localização_CEN",
    "Localização_CON",
    "Localização_GRA",
    "Localização_ILC",
    "Localização_ING",
    "Localização_ITA",
    "Localização_ITP",
    "Localização_JBV",
    "Localização_JUR",
    "Localização_LAG",
    "Localização_PBL",
    "Localização_SAN",
    "Localização_SLA",
    "Localização_STO",
    "Localização_TBM",
    "Localização_UFSC",
]

FEATURES_REVENUE_MODEL_Q1 = [
    "Categoria",
    "Quartos",
    "year",
    "month",
    "day",
    "holiday",
    "day_of_week_Mon",
    "day_of_week_Sat",
    "day_of_week_Sun",
    "day_of_week_Thu",
    "day_of_week_Tue",
    "day_of_week_Wed",
    "Localização_BOM",
    "Localização_CAM",
    "Localização_CAN",
    "Localização_CEN",
    "Localização_CON",
    "Localização_GRA",
    "Localização_ING",
    "Localização_ITA",
    "Localização_ITP",
    "Localização_JUR",
    "Localização_LAG",
    "Localização_PBL",
    "Localização_SAN",
    "Localização_STO",
    "Localização_TBM",
    "Localização_UFSC",
]
